name: Joe Conley
title: Joe Conley
url: http://www.josephpconley.com
description: Random thoughts on technology, books, golf, and everything else that interests me

paginate: 10
paginate_path: "/page:num"

gems: [jekyll-paginate, jekyll-gist, github-pages, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
future: true

collections:
  tag_pages:
    output: true
    permalink: /tags/:name/
  tag_feeds:
    output: true
    permalink: /tags/:name/feed.xml

defaults:
  -
    scope:
      path: ""
      type: tag_pages
    values:
      layout: tag_index
  -
    scope:
      path: ""
      type: tag_feeds
    values:
      layout: tag_feed