name: Joe Conley
title: Joe Conley
url: http://www.josephpconley.com
description: Random thoughts on technology, books, golf, and everything else that interests me
paginate: 10
paginate_path: "/page:num"
gems: [jekyll-paginate, jekyll-gist, github-pages, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
future: true